{% set name = "Chart.js" %}
{% set version = "2.9.4" %}
{% set sha256 = "62aa1328122831cca274054762ef2050ee189d982b027d37a96e864a1961f669" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chartjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g chart.js
  requires:
    - nodejs


about:
  home: https://github.com/chartjs/Chart.js
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Simple HTML5 Charts using the <canvas> tag
  description: |
    Simple HTML5 Charts using the <canvas> tag  
  doc_url: http://www.chartjs.org/
  dev_url: https://github.com/chartjs/Chart.js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
