{% set name = "Chart.js" %}
{% set version = "2.8.0" %}
{% set sha256 = "030cfc67940ad0b6c3f035a27ef39acae0dd39b188b1f73872cbb161dc782d04" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chartjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g chart.js
  requires:
    - nodejs
   

about:
  home: https://github.com/chartjs/Chart.js
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Simple HTML5 Charts using the <canvas> tag'
  description: |
    Simple HTML5 Charts using the <canvas> tag  
  doc_url: http://www.chartjs.org/
  dev_url: https://github.com/chartjs/Chart.js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
