travis:
  secure:
    BINSTAR_TOKEN: QMXF1bmD3IH8qs6wHKsRSA92B0rsILTVg24deyB2YOCjGl3H55BSICgC3QobdWP9//SR6Xo9PnVJdr7v3PvwmDiM1E7OsLeO47sqNv4UtVRzFoup+JD+qQgpcM1HjcTe3/ffvM91krEPs8ATHy8KEz4aFeGK6c/cEFoI8z1y0VBlvclJ9luV5sIDgUW8wyT5XmdTTj9nMUuA78eeOHQ5tUK6UfgJnmwEpjCeE9+5IkQepSPDGqd03MjsmoPq/cGoj9f3yHFn5bFJn44SJp7qfZUl4acInEun757Pu/AgrbBX4usio6HDG0N6tSrwnL1QM0+eEfRmmK+agnPk8OUqlqFOJ/9qgxx/ymOERu+MY3u1M2VLPDZVawaSN2acx6tHmNBr7QoJshsGSdoqvuDywaZjO00seXgQ300kAfcNzpFPi239TRuBKzNdm2n5d1bRdCbQ+gjbHDlc+0TWAL0bAZuyfqDp16sBmMUHOuOi7hvXm0ioU5ZEEpftmxCsv8b0rGfkTqjlvEzkPRliowQchUwfUybTsWlgsWISdDscMFivrGU/w3M28AxyzbP/9JnLJsDUPKSNf4KF4GpMDTwe8rM5EiaKEDbUZY4HtxrgJ8y/9YI3ycHLGUNLrYrPgbGNY9VF8qEXXJzogJpux/BWKCjX1iFTCOKSSUfWSz7AW8E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
