travis:
  secure:
    BINSTAR_TOKEN: dT5gsJYxU4g0doJo5741oTCDiHsYqyPaFQGXJskE6vyeypLBQNGid1Q9t7hiM21sYMTKijzkv2lD0V5QJtzdOktNa1P3PPq0d8B/o6AcA7JV6vX3/82BvIhOIZYiI5AwpHuMrmDWZNk4UaoJo+5tDQLggVYlxWCYbz7Rbek1OXdG0VpiW0VJXdeli+G7PMVrHMdlzZ81bgkUzWaL9T520b/Blvm+y1SRmFx8N2D1tiRJrLsvj/MYv1fIXnr1p5UgbryMmVuMtlWRU80bN2LGtmikFKxFudSiosO8YRKqvon0u7CMuncXbIsreUB9zL1RtgMYwcggdyOs+bdDGVB+xGwRlS9sVzoSMIBv6OCDZXLlYDkLa07g3b6EKV9Ls+PAwBcpkNjiZqTkHl95+rlC93VW/laz5SRYbQjneCL+VXt1FyE5PdhG8UEwu1zNeqWiHlI4yhKSb0X9bDBnfNojzgCtYIeOJFBeoVPnz0+CNZSVDt85BcrxZwjWaMTZzgsmDz6k7aQkpjhHJUNvsJYvKoXWOYSxe8DiB/GI5pT5VdjczPJnfLrxABbUwb4Ctjwh0Inve+sl4ZH76yRVo03mnvoDpuFiC01XqLU5KWgDGLGUxkLiYnvG9yVLQoxEitHVsCNQkvbm/wnO+4h1/YC/fp1UW9kg3+c8nVAwPAl16J4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
