travis:
  secure:
    BINSTAR_TOKEN: rXjtX/1u9wgRTCVtfiXQYP35h7O+CZM7TYvZNd2DU5PEyudgyQ41PHVqWdIrBAkUqfJ5jO+2WETATDpONIIzhSRmkXBR1NBV4h80Nx+jfAL8IHWTyUPfC40MvMJCFQB5eAlkoRsobMrUF6k+ETb6B3rXTog6jZPs6LrDSgvxkokiggp4k0bzOhjkMVv82k/3APrT22stQ+NK7ESniaHcxM8mwpdtH5DRCfHGlQJRoJpXfQkYvlKXSiDlnG1mEzSJSglJXX4jwBvsQXkJ+nN19GvrowDfrfwhrNlDa+y6wtX4dD5bG7jsJ78OFmJyi5fyb5n54bfj3CUA7g+IAOiBU+YMBc2gyZYo5sJCGNYaEMuIaoLDxkPTF5l4yu8x+wgGrntjGMuKggXhsRZAzT/2B7xsKdMcMYPoPU+5Rk5+8qEU0+s8SV2dcZgUSG1g1yTh7pQu+URzkW6sFXfSyO50caUWnT2QQdt/SIQFw4Dqn2Jw06ICGtuM9C23EwVJ8n25FTyphT3s8i8/nOpuKvOp8ancAa15op7+acn7PKXoq+R4xAOGXJGDYdwhlldonhlLOwaHGqOaGCwfczy4uq8wwztaCzY1NfO99PPXmO4dlqEJI6s8LJFwxUNIG2MxWKmVff+fWa+AJbr4lPjLlckEVLMqGighHKbwREuRrkzs+ds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
