travis:
  secure:
    BINSTAR_TOKEN: L/DTxXbi6NmSMOrwXg0jbcXI1d+HszVf5oKqt5J3mWgX3TvZmp7GsVKWK0XOts2jrPT6FbJWpnApAUA/h3C9c8ci5WgWl1LdxsaMara52i7yoQGq0g/xpgmQfoIUI23eLzzsr4Yij6UK0/40L/C/6z/Dl2Nc9D0nn9LODtl0EHuYRB4Zu0cCP9pwBMTGjAzy/4TZd6vPDRg7zP6ckSGFotHBGwe6+E40u8zg3CcQJbn2DI4OpuFrsRViAoo+12rNHzsZQllx4zJbPAicw5I2v/broarJFtG4e3wgPRPjLubvnYSbwIPVKmwKG3VoLpXb3jdfIUCV6izUQuRUzcAiW26aq3uyAbmJdE5JcICaKiSWqw3har0ldd1jdu6Orv46M5/qmX/T/bz7YfWkK3JcX2A82a3fKF6YFkUvEft4kiARQoIEmKKGwcO6D2g7Frn4SIjuyVzv6NARaHx3THEUULtBIDmY/0G7jYZ6udDU50j6jUC3l2RtknzTgy9GOwTjGurC0yx0sju0zdbdaBtLMi1Rg/jY4DRYxLOsJyfvD2/90qsg5BHU+/Ansdqak3gedhm5EYDjmVl2iGGJja2Z8UnePUz44W0pzYoXJ3YFUL0ucuG9pGe+hOUcHgxt6H77EF+sahw+4u/IEqf1DV0/Mt4xGcS96mQZaylZ1dujm20=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
